- Cargo.lock
- docs/getting_started.md
- docs/json.md
- src/build.rs
- src/project.rs
- Fix building when `./include` folder does not exist (eg. no CBA includes or different name)
- Expose include folders to `hemtt.json`
- Print pretty errors from armake2 and gracefully handle them
- Move `keys` from root to `releases/keys`
- Shall be made configurable one day
> Check include folders and expose to configuration

- Cargo.lock
- Cargo.toml
- src/build.rs
- src/main.rs
Uses rayon to multithread building of mods and optionals by folder.
Accepts `-j` and `--jobs` flags to change at runtime. Defaults to number
of logical processors.
Authors: bovine3dom and jonpas. Squashed for clarity.
NB: untested on Windows. Works fine on Linux.
Closes #13.
> Add multithreaded build

- src/build.rs
Fix #43.
When/if I get round to #41 I'll separate out this "walk this directory, look for this filetype or directories, apply this function to all of them using the thread pool" into a nice function which we can use all over the shop. I think we can stomach the repetition for now.
> Sign optionals in parallel

- docs/json.md
- src/build.rs
- src/files.rs
- src/project.rs
- Work on #17 
- Add configurable header extensions
- Add configurable signature name (the middle part between PBO name and ".bisign")
- Add configurable mod name (`@mod` folder name)
- Add configurable key name (`.bikey` and `.biprivatekey` names)
- Add initial replacement patterns for header extensions and signature name properties (will be expanded in the future either with custom handling or [handlebars](https://github.com/sunng87/handlebars-rust) - thus the syntax)
- Change signing to print pretty errors from armake2 instead of panic on failure
Git hash parser can be added in separate PR as utility, otherwise this will get too big. Zip utility will also need it for parsing zip name.
> Add configurable header extensions, signature name and mod name

- .dockerignore
- Dockerfile
- Decrease the image file size
- Remove rust from docker image - should probably not need it in CI pipelines with hemtt
- Speed up Docker build by ignoring some directories
> Use multi stage build for Docker image

- Cargo.toml
- appveyor.yml
- ci/before_deploy.ps1
- ci/wininstaller.iss
- Close #26 
- Add a windows installer to all tagged releases
> Windows Installer

- Dockerfile
ca certificates is necessary for running hemtt create due to the call to github with `create_include`
> Install CA Certificates in Dockerfile

- src/build/sign.rs
- Fix ACE3 `tracers` panic on release build
ACE3's `tracers` optional caused panic on release build, due to including the prefix `ace` (`trACErs`).
I am not sure this is the ideal solution, but I think it was intended to check only start anyways.
> Fix sign pbo file prefix check

- src/main.rs
`convertproject` wasn't listed under `--help`
> Document convertproject on help

- docs/project.md
- rustfmt.toml
- src/build/mod.rs
- src/build/release.rs
- src/build/sign.rs
- src/main.rs
- src/project.rs
Closes #42.
~~I haven't left writing the private key to disk as an option. The only valid usage I can think of is if you needed to distribute signing across a server farm, which you don't.~~
~~I've cheekily made the public key follow the `name_version.bikey` format since there will be a different one for each version now.~~
~~I've just spotted #47. I'm happy to rebase this on that once it has been merged.~~
---
- Don't write private key to disk unless `reuse_private_key` is set to true in the project configuration
- If it is set to true, revert to the old behaviour
- Change the default key name to include the version if `reuse_private_key` is false, stick with old default otherwise
- Split copy / sign up into separate functions and do a bit of tidying up (I went a bit off-piste, sorry...)
> Don't write private key to disk

- docs/project.md
- src/build/sign.rs
- src/project.rs
- Use V2 Signatures by default
- Add project level setting `sigversion`
> default to v2 signatures

- Cargo.lock
- Cargo.toml
- src/utilities/zip.rs
- Replace #133 
- Optimize `zip` utility (better than #133)
- Using `flate2` (DE)FLATE implementation in `zip-rs` from [`jonpas/zip-rs [flate2]`](https://github.com/jonpas/zip-rs/tree/flate2) instead `libflate`
- Ref. https://github.com/mvdnes/zip-rs/issues/88#issuecomment-491185791 and https://github.com/mvdnes/zip-rs/pull/107
In debug build, compared to #133, shaved off another ~30%. `release` build compression speeds are now on-par with 7z on Windows.
All benchmarks were ran on `release` build (`cargo build --release`).
- **Old**: HEMTT 249d6e8a37a3390a798bd7ad98bf9313b1dc2297
- **#133**: Pull request #133 (`BufReader`/`BufWriter`/`copy` optimization)
- **New**: **#133** + `flake2` implementation in `zip-rs` (instead of `libflate`)
_Difference in …
> Optimize zip using flate2

- src/build/mod.rs
- Try to find any config includes in the current directory before trying other paths in include folders
> Always set current path as first include folder

- src/main.rs
- Fix crash when no arguments are provided
```thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e\src\libcore\slice\mod.rs:2686:10```
> Fix crash when no arguments are provided

- docs/project.md
- src/build/release.rs
- src/build/sign.rs
- src/project.rs
- Build (by default) optionals into their own mod folders, allowing users to directly launch them.
- Cleanup `fn release` a bit
- Base release folder variable
- Filtering for files only
- Pass path directly to `copy_sign`
Used in ACE3 and other projects - easier to do in HEMTT than custom build scripts, also makes more sense. Enabled by default, possible to disable.
TODO:
> Support Launchable / Folder Optionals

- src/main.rs
- Exit with non zero status code if any addons fails to build
> Exit with error if any addons fails to build

- src/render/helpers/mod.rs
- Close #73 
There isn't a good way to handle this with an error without just exiting the whole program instantly. The best solution for now is to specify defaults
> Specify defaults for helpers

- docs/usage.md
- src/addons/location.rs
- src/addons/mod.rs
- src/commands/build/checks/clear.rs
- src/commands/build/mod.rs
- src/commands/clean.rs
- src/commands/mod.rs
- src/commands/pack.rs
- src/commands/status.rs
- src/lib.rs
- src/project/addons.rs
- src/project/mod.rs
- Add ability to specify addons to build
Examples
```
hemtt build
addons/*, optionals/*, compats/*
hemtt build all
addons/*
hemtt build zeus music
addons/zeus, addons/music
hemtt build --opts maps
optionals/maps
hemtt build zeus --opts maps music
addons/zeus, optionals/maps, optionals/music
hemtt build all --opts maps
addons/*, optionals/maps
hemtt build --compats maps
compats/maps
hemtt build all --compats maps
addons/*, compats/maps
hemtt build all --opts music zues --compats maps
Builds addons/*, optionals/music, optionals/zeus, compats/maps
hemtt build all --opts all --compats maps
addons/*, optionals/*, compats/maps
```
> --opts & --compats

- appveyor.yml
- ci/wininstaller.iss
Move Hemtt.exe to subfolder when installed via the setup to remove uninst00.exe/dat from command line
> Fix Installer Folder Struture 

- docs/project.md
- src/commands/build/postbuild/release.rs
- src/macros/fs.rs
- Finish all set goals of #88
- Support copying directories specified in `files` in 2 ways:
- Specified folder into root of release folder
- Example: `"extras/plugin` -> `releases/<version>/@<mod>/plugin`
- Specified folder with mirrored structure (`/` at the end)
- Example: `"extras/plugin/` -> `releases/<version>/@<mod>/extras/plugin`
> Support directories in files configuration

- docs/scripts.md
- src/commands/build/mod.rs
- src/commands/pack.rs
- src/flow/script/mod.rs
- src/flow/script/task.rs
- Allow setting build scripts to only run during release build or only during development build (use: versioning). - close #297 
- Update Scripts documentation (partially).
- Add `check` build step.
- Compact table.
Made use of existing but unused `release` property.
Implementation could probably be nicer, mostly how to pass information on build type to the script. Feedback is welcome.
> Support running build steps in release-only or development-only

- .github/workflows/rust.yml
- Title
OpenSSL was just updated to 1.1.1e today. URL to 1.1.1d is no longer available as https://github.com/synixebrett/HEMTT/runs/516625275?check_suite_focus=true#step:4:13 shows.
> Udpate OpenSSL to 1.1.1e in CI

- src/commands/build/postbuild/release.rs
- Expand #295 for files (not just directories)
- Allow specifying file configuration as such:
- Specified file into root of release folder
- Example: `"extras/test.txt` -> `releases/<version>/@<mod>/test.txt`
- Specified file with mirrored directory structure (`/` at the end)
- Example: `"extras/test.txt/` -> `releases/<version>/@<mod>/extras/test.txt`
Required for ACRE2.
> Support file directory mirror in files configuration

- src/utilities/filepatching.rs
- Fixes a Issue when a Empty Folder called Arma 3 is in a Steam Library folder
Sometimes when Steam moves Installation folders a Empty folder persists and does not get deleted. HEMTT used the first Arma 3 Folder it could find even when it was empty.
When searching for the Executable instead to be sure it is the Arma 3 installation
> Prevent file-patching to Empty Arma Folder

- .github/workflows/rust.yml
- Fix Windows builds and avoid manually changing the URL when OpenSSL is updated in the future
> Install OpenSSL using Choco for Windows GitHub Actions

- README.md
- Added unoffical download link and instruktions for a windows package manager
Exsample usage:
```powershell
~ PS> scoop bucket add Arma3Tools https://github.com/ColdEvul/arma3-scoop-bucket.git
Checking repo... ok
~ PS> scoop install hemtt
Installing 'hemtt' (0.7.6) [64bit]
hemtt-v0.7.6-x86_64-pc-windows-msvc.zip (8.1 MB) [============================================================] 100%
Checking hash of hemtt-v0.7.6-x86_64-pc-windows-msvc.zip ... ok.
Extracting hemtt-v0.7.6-x86_64-pc-windows-msvc.zip ... done.
Linking ~\scoop\apps\hemtt\current => ~\scoop\apps\hemtt\0.7.6
Creating shim for 'hemtt'.
'hemtt' (0.7.6) was installed successfully!
```
> Added unoffical download link and instruktions 

- bin/libs/error/src/lib.rs
Use `PrettyError::brief` if possible
> Display errors using brief

- libs/preprocessor/src/lib.rs
- libs/preprocessor/tests/bootstrap/comment_edgecase/expected.hpp
- libs/preprocessor/tests/bootstrap/comment_edgecase/source.hpp
Fixes issue where the `tokenstream` cursor would not be moved back when `peek_forward` is called but the next token isn't an slash.
- Fixes #462
> Fix sqf preprocessor comment edge case

- Cargo.lock
- bin/Cargo.toml
The `fully-switch-from-vdf` branch got released under 2.0.0-alpha.0
> Switch to the 2.0.0-alpha.0 steamlocate release

- bin/src/utils/link.rs
Fix compatibility with network drives (UNC paths). Related to #338.
Maybe can just do directory symbolic link at all times? They mostly behave the same.
> Fall-back link creation to directory symbolic link

- bin/src/modules/hook/mod.rs
Maybe got missed when HEMTT config got moved to `.hemtt` sub-folder? Documentation says it should be "root of the project", so that's what this PR does.
> Fix `HEMTT_DIRECTORY` hook constant

- bin/Cargo.toml
Fix:
```
warning: <path>/bin/Cargo.toml: dependency (time) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
warning: <path>/bin/Cargo.toml: unused manifest key: dependencies.time.verison
```
> Fix dependency (time) specified without providing version (typo)

- book/rhai/hooks/examples.md
There might be a better way to do this? Maybe we could get `is_archive()` or something, that way we could skip a hook if the flag was actually given, and still get a proper error if the flag was not given and zip also didn't exist.
> Support --no-archive in rename zip example hook

- bin/src/config/project/version.rs
Right now HEMTT-based projects must lie within the top level of a git repository for git hash extraction to work, this PR changes this to allow HEMTT-based projects to lie in any subdirectory below the VCS root as well.
Useful when using one git repo to version multiple related things at once (e.g. compiled components, art, models, etc) where mod-related files exist as a subdirectory within the main project.
> Allow projects to be within subfolders within VCS

- bin/src/modules/pbo.rs
- bin/src/modules/sign.rs
This is a follow up to my previous PR (#533) where I missed a few places that `Repository::open` was being used instead of `Repository::discover` causing `hemtt dev` to work but `hemtt release` to fail (during PBO signing) if the project is in a subfolder.
Apologies for not thoroughly testing my changes earlier.
> Fix build/release commands when project is a subfolder in VCS

- .github/workflows/build.yaml
Runs on Linux in CI so path must use Linux path too...
> Fix Chocolatey pack path for Linux CI

- bin/src/modules/rapifier.rs
- libs/preprocessor/src/codes/mod.rs
- libs/preprocessor/src/codes/pw2_invalid_config_case.rs
- libs/preprocessor/src/processor/mod.rs
- Turns `config.cpp` of any case into `config.bin`
- Warns if `config.cpp` is not all lowercase
- Closes #562
> Config: case warning

- bin/src/executor.rs
- bin/src/modules/binarize.rs
Fix path from #590. Tested only on CUP, ~~it might go a folder too high in other mods? That would still work though~~.
> Binarize: fix copy files from addons folder path 

- bin/Cargo.toml
- bin/src/error.rs
- bin/src/modules/hook/libraries/project.rs
- bin/src/modules/hook/libraries/rfs/path.rs
- bin/src/modules/hook/libraries/vfs/path.rs
- bin/src/modules/hook/mod.rs
- bin/tests/bravo/.hemtt/hooks/post_release/03_dirs.rhai
- book/rhai/library/filesystem.md
- book/rhai/library/project.md
- `.list()` array of files in a directory
- `.file_name()` returns the file / dir name
- `.parent()` returns the parent of the path
- `HEMTT.project().mainprefix()`, return main prefix or empty string if not set
> hooks: more rhai fs functions

- Cargo.lock
- bin/Cargo.toml
- bin/src/commands/utils.rs
- bin/src/utils/inspect.rs
- bin/src/utils/mod.rs
- bin/src/utils/verify.rs
- libs/pbo/src/model/mime.rs
Inspect PBOs, Signatures (.bisign), and Public Keys (.bikey)
> Utils: Inspect

- bin/src/modules/hook/mod.rs
- book/commands/index.md
- book/getting-started/index.md
- book/rhai/library/filesystem.md
- book/rhai/library/hemtt.md
> rhai: rfs in all phases

- bin/src/modules/asc.rs
.inc.sqf get copied to temp for asc building
```
compile AppData/Local/Temp/hemtt/DEV_CBA_A3/asc/output/x/cba/addons/ui/initSettings.inc.sqfc
[ERR] [L2|C9|/x/cba/addons/ui/initSettings.inc.sqf]	Parse Error: syntax error, unexpected (, expecting ] or ","
```
when it fails it triggers output
` WARN ThreadId(01) ASC 'Parse Error' - check .hemttout/asc.log`
> ASC - Don't copy .inc.sqf for building

- bin/src/commands/launch/mod.rs
- book/commands/launch.md
- libs/common/src/project/hemtt.rs
Improve support for directly launching into 3DEN with an existing mission by allowing missions contained in the project to be used.
Adds a `mission` configuration parameter that specifies whether a launch configuration loads directly into a mission. Can be specified as either:
- a folder name in `.hemtt/missions/` (e.g., `mission = "test.VR"` would launch `.hemtt/missions/test.VR/mission.sqm`).
- a relative path to a `mission.sqm` file (or folder containing it).
Tested all of the various cases and everything looks good. I am not too familiar with Rust and this is just the result of my messing around. So, the code could probably be improved.
Close #621
> Improve support for direct mission launching

- bin/src/modules/hook/libraries/rfs/path.rs
- bin/src/modules/hook/libraries/vfs/path.rs
- book/rhai/library/filesystem.md
Implements #634 
Creates the directory.
```ts
HEMTT_VFS.join("docs").create_dir(); // Creates the docs folder
```
Creates the directory and all parent directories.
```ts
HEMTT_VFS.join("docs").join("images").create_dir_all(); // Creates the images folder and the docs folder if they don't exist
```
Removes the directory.
```ts
HEMTT_VFS.join("docs").remove_dir(); // Removes the docs folder
```
Removes the directory and all its contents.
```ts
HEMTT_VFS.join("docs").remove_dir_all(); // Removes the docs folder and all its contents
```
> Hooks: Directory commands

- bin/src/modules/rapifier.rs
Fix #658
This should probably be a proper report but this is still fine for now
> show full path for cpp warning

- bin/src/modules/binarize/mod.rs
I don't know what I was thinking when I wrote this... the command exe was already in an option.
When will I stop fixing HEMTT bugs in the middle of the night (and introducing new ones simultaneously)? Never.
Binarize was broken on linux? Fixed by silently skipping on all platforms... Fixes #660
> fix binarize not running on 1.11.1

- Cargo.lock
- bin/src/commands/launch/error/bcle1_preset_not_found.rs
- bin/src/commands/launch/error/bcle8_mission_not_found.rs
- bin/src/commands/launch/mod.rs
- book/commands/launch.md
- libs/common/src/arma/dlc.rs
- libs/common/src/project/hemtt.rs
- libs/common/src/project/mod.rs
- libs/common/tests/config.rs
- libs/common/tests/config/extends.toml
Adds `extend` to `hemtt.launch`, which will append the arrays and overwrite keys in previous layers. Can be recursive (if you make a loop that's your fault)
> launch: extend configs

- .github/workflows/browser.yaml
- .github/workflows/build.yaml
- .github/workflows/coverage.yaml
- .github/workflows/lint.yaml
- .github/workflows/test.yaml
`CODECOV_TOKEN` secret will have to be added for the codecov action update. See https://docs.codecov.com/docs/adding-the-codecov-token#github-actions
> CI - Replace deprecated actions-rs and update actions

- bin/src/modules/sqf.rs
- libs/common/src/lib.rs
- libs/common/src/strip.rs
- libs/workspace/src/path.rs
- Fixing an issue with locating full paths within a workspace with a mix of capitalization on Linux
> Workspace: insensitive strip prefix on linux

- libs/sqf/src/analyze/if_assign.rs
SAA1
```
38 │ if (isNil "x") then {5} else {x};
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use select
│
= note: the if and else blocks only return constant values
select is faster in this case
= try: [x, 5] select (isNil "x")
```
the replacement is not safe in scheduled
```
[] spawn {
[x, 5] select (isNil "x")
};
Error Undefined variable in expression: x
```
> Analyze - Skip SAA1 suggestion if consts used in `isNil` check

- bin/src/commands/value.rs
- bin/src/context.rs
- bin/src/modules/archive.rs
- bin/src/modules/asc.rs
- bin/src/modules/binarize/mod.rs
- bin/src/modules/files.rs
- bin/src/modules/hook/libraries/project.rs
- bin/src/modules/hook/mod.rs
- bin/src/modules/pbo.rs
- bin/src/modules/rapifier.rs
- bin/src/modules/sign.rs
- bin/src/modules/sqf.rs
- book/configuration/p-drive.md
- libs/common/src/arma/dlc.rs
- libs/common/src/project/hemtt.rs
Closes #700 
`hemtt check` can have a separate PDrive requirement, useful for CI
> check: specify pdrive requirement

- bin/src/modules/binarize/mod.rs
Closes #708 
`HEMTT_BINARIZE_PATH` can be set to the folder that contains `binarize_x64.exe`
> binarize: specify folder

- libs/sqf/src/compiler/mod.rs
- libs/sqf/src/compiler/serializer/mod.rs
- libs/sqf/src/lib.rs
- libs/sqf/src/parser/mod.rs
- libs/workspace/src/reporting/processed.rs
- Uses code offsets, saves space and Arma is broken for using constants
> SQF: Working compiler

- libs/config/src/analyze/codes/mod.rs
- libs/workspace/src/reporting/diagnostic/mod.rs
Noticed https://github.com/IDI-Systems/acre2/pull/1335 had config error but no message
Can repoduce with open `class x {`
- With semicolon as last char in file
```
class CfgVehicles {
class a {
};
```
```
ERROR panicked at libs\config\src\analyze\codes\mod.rs:54:40:
index out of bounds: the len is 1912 but the index is 1912
```
- With newline or comment at eof
```
class CfgVehicles {
class a {
};
//test
```
No error messages, ends with ` INFO Rapified x addon configs`
but it returns error code 1 and `-vv` shows `TRACE phase: pre_build (Rapifier) (failed)`
PR makes it return an error on EOF error
```
error[CCHU]: found end of input but expected one of "8", "Y"....
```
> config: Show EOF errors and fix seg fault

- libs/preprocessor/src/parse/mod.rs
- libs/preprocessor/tests/bootstrap.rs
- libs/preprocessor/tests/bootstrap/comment_in_quote/expected.hpp
- libs/preprocessor/tests/bootstrap/comment_in_quote/source.hpp
e.g. url inside single quote string
```
error[SPE1]: invalid token
1 │ _ctrl htmlLoad 'https://zombo.com/';
│                      ^ invalid token
```
the `//` was treated as a comment and the rest of line was cutoff (so just `'https:`)
I am not positive on my change to parsing logic and changes should be carefully looked it,
but it seems to pass all tests
> parse: fix `//` inside single quote strings

- libs/workspace/src/reporting/processed.rs
fixes
`if (true) then { a } else { b };`
```
push true
callFunction if;
push [{},{}]
callOperator then
```
I couldn't find any examples of the `warn` triggering, so I don't see any harm in adding it
> workspace: fix span extraction with length of 1

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- Uses HEMTT's sqf compiler by default
- `--asc` to use ArmaScriptCompiler
- `--expsqfc` is removed
> sqf: use hemtt's compiler

- bin/src/commands/dev.rs
- bin/src/commands/launch/mod.rs
- book/commands/launch.md
- libs/common/src/config/project/hemtt/launch.rs
Closes #735 , Alternative to #739, I don't know why we didn't just think of this earlier
> launch: add more config options

- libs/sqf/src/compiler/mod.rs
maybe alt to #754
I think we still need https://github.com/BrettMayson/HEMTT/pull/748 for extracting vars that are single chars
cba/ace builds using this seem to work fine, but I don't have full confidence
> sqf: fix serilizing empty code

- bin/src/utils/sqf/case.rs
flush buffer if file ends on a char (no whitespace/newline)
e.g. https://github.com/BourbonWarfare/POTATO/blob/master/addons/bodyCleanup/functions/fnc_getPlayerViewCones.sqf#L48
it would delete the last `_viewCones`
> utils: fix sqf case util when code doesn't end with whitespace

- libs/sqf/src/compiler/mod.rs
- libs/workspace/src/path.rs
compiled file paths should be relative to arma not the project
e.g.
before: `/addons/main/test.sqf`
after: `/a/b/addons/main/test.sqf`
> sqf: Compile relative arma file paths

- libs/sqf/src/compiler/mod.rs
- libs/workspace/src/reporting/processed.rs
Fixes two problems with sqfc offsets
Shouldn't be any functionality change, just effects arma errors and debugging.
- It would use the macro's start location
```
from sqf:
#define IS_META_SYS(VAR,TYPE) (if (isNil {VAR}) then {false} else {(VAR) isEqualType TYPE})
#define IS_STRING(VAR)   IS_META_SYS(VAR,"STRING")  
before (nonsense because it's using the index of start of macro for both sub blocks):
push [{(if (},{(if (isNil {_pos}) then {fa}]
after:
push [{false},{(_pos) isEqualType "STRING"}]
```
- Unicode would cause problems, as arma seems to expect bytes
e.g. the `#` is in the wrong location
before:
after:
> sqf: Fix sqfc byte offset

- book/utilities/sqf/case.md
`hemtt utils sqf case` was missing a page in the book.
I don't know what all other setup is required other than creating the markdown file itself.
> Book: Add SQF page for `hemtt utils sqf` command(s)

- libs/sqf/src/parser/mod.rs
- libs/sqf/tests/lints/s05_if_assign/source.sqf
- libs/sqf/tests/lints/s05_if_assign/stdout.ansi
Trailing comma in arrays cause script errors (when using non-compiled//filepatching)
```
Error in expression <x = [1,2,]>
Error position: <]>
Error Missing [
```
> sqf: Don't allow trailing commas in arrays

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/modules/sqf.rs
- bin/tests/build.rs
Hasn't been any problems I've seen.
I think there is no reason to have an option not to use the optimizer, if we ever add any new optimizations we are unsure of, they should be behind their own --exp flag for testing
> sqf: enable optimizer by default

- libs/sqf/src/analyze/lints/s18_in_vehicle_check.rs
- libs/sqf/src/analyze/lints/s22_this_call.rs
- libs/sqf/src/analyze/lints/s23_reassign_reserved_variable.rs
- libs/sqf/tests/lints.rs
- libs/sqf/tests/lints/s23_reassign_reserved_variable/source.sqf
- libs/sqf/tests/lints/s23_reassign_reserved_variable/stdout.ansi
> sqf: prevent changing reserved variables

- libs/sqf/src/compiler/optimizer/mod.rs
Floods the logs with traces which will mean nothing to anyone not developing HEMTT
Now the trace! is only added with `debug_assertions` (testing and building locally)
> sqf: optimizer should trace only when testing

- libs/sqf/src/analyze/lints/s24_marker_spam.rs
- libs/sqf/tests/lints.rs
- libs/sqf/tests/lints/s24_marker_spam/source.sqf
- libs/sqf/tests/lints/s24_marker_spam/stdout.ansi
> sqf: prevent marker spam

- libs/common/src/prefix.rs
- libs/workspace/src/lib.rs
Checks `/include/`, `/optionals/`, `/addons/` for prefix files instead of `/`
Adds a new error if there are any duplicate prefix files
> workspace: fix pointer scanning, add duplicate prefix error

- book/README.md
Since the book is now available under a different link it might not be clear that the source code is available on GitHub.
> Added link to github

- bin/src/commands/localization/sort.rs
- bin/src/modules/stringtables/mod.rs
- libs/stringtable/src/analyze/lints/01_sorted.rs
- libs/stringtable/src/analyze/mod.rs
> localization: handle subaddons

- libs/stringtable/src/analyze/lints/01_sorted.rs
- libs/stringtable/src/lib.rs
> stringtables: add trailing newline, trim for comparisions

- Cargo.lock
- libs/stringtable/Cargo.toml
- libs/stringtable/src/lib.rs
- libs/stringtable/tests/snapshots/ace_arsenal__sort-2.snap
- libs/stringtable/tests/snapshots/ace_arsenal__sort.snap
Comments will be preserved and attached to the line following them
> stringtables: preserve comments

- bin/src/commands/script.rs
- bin/src/modules/hook/libraries/hemtt.rs
- bin/src/modules/hook/mod.rs
- bin/tests/bravo/.hemtt/hooks/post_release/02_test_rhs.rhai
- bin/tests/bravo/.hemtt/scripts/test.rhai
- book/rhai/scripts/index.md
- libs/workspace/src/reporting/diagnostic/label.rs
> hooks: ability to call scripts

- libs/preprocessor/src/processor/defines.rs
- libs/preprocessor/tests/warnings.rs
- libs/preprocessor/tests/warnings/pw3_padded_arg_inner/source.hpp
- libs/preprocessor/tests/warnings/pw3_padded_arg_inner/stderr.ansi
Fixes #642 
Honestly not sure if there's a cleaner more clever solution but this one works just fine. Please let me know if this is not adequate and or if there's anything you'd like to see changed.
> preprocessor: fix duplicate pw3_padded_arg warnings

- bin/src/context.rs
- bin/src/lib.rs
- bin/src/logging.rs
> project: don't create .hemttout when not needed

- Cargo.lock
- bin/Cargo.toml
- bin/src/main.rs
- bin/src/windows_message.rs
- hls/package-lock.json
- hls/package.json
- libs/preprocessor/src/parse/mod.rs
- libs/preprocessor/src/processor/mod.rs
[message.webm](https://github.com/user-attachments/assets/bb8a5f36-4acc-4f8f-acce-e6a2a4066a1c)
Text in the video is outdated
also formats some stuff that was sent straight to main, whoops
> general: checks for usage outside of a terminal on windows

- libs/config/src/analyze/lints/c11_file_type.rs
- libs/config/tests/lints/c11_file_type.hpp
- libs/config/tests/snapshots/lints__config_error_c11_file_type.snap
- Assume that values without `\` are classes
- Change `allow_no_extension` to false by default
- Closes #851, probably
> config: file type check ignores classes

- libs/config/src/analyze/lints/c11_file_type.rs
Always allow no extension when the path starts with \a3, as it is probably just copy pasted
> Config - c11 ignore a3

- libs/sqf/src/analyze/lints/s22_this_call.rs
The performance difference is minimal, and people seem to prefer with `_this`
Perhaps this can be done in the optimizer instead?
> sqf: disable _this call lint

- Cargo.toml
- bin/src/lib.rs
- libs/workspace/src/reporting/processed.rs
Fixes the performance regression from #892 
mapping() is still a really expensive function, but it's once again only used for generating error messages, and it's good enough for that
> preprocessor: cache line mappings for clean output

- bin/src/modules/stringtables.rs
- libs/stringtable/src/lib.rs
- Adds a progress bar and `INFO Checked {} stringtables` messages
- Improvements to finding stringtable key positions, less allocations
- Processes the stringtables in a parallel iterator
Shaves another 800ms off on my machine
> stringtables: less allocation, threads

- bin/src/modules/rapifier.rs
- libs/config/src/analyze/lints/c12_math_could_be_unquoted.rs
- libs/config/src/lib.rs
- libs/config/src/model/mod.rs
- libs/config/tests/lints.rs
- libs/config/tests/lints/c12_math_could_be_unquoted.hpp
- libs/config/tests/lints/project_tests.toml
- libs/config/tests/snapshots/lints__config_error_c12_math_could_be_unquoted.snap
Adds pedantic lint for quoted math statements that hemtt could handle
```
help[L-C12]: Math could be unquoted
┌─ addons/main/config.cpp:5:28
│
5 │         requiredVersion = "2 + 0.18";
│                            ^^^^^^^^ reducible to: 2.18
│
= note: Could remove quotes to allow evaluation at build-time
```
> config: Add lint C12 for quoted math that could be run at build-time

- libs/config/src/analyze/lints/c13_config_this_call.rs
- libs/config/tests/lints/c13_config_this_call.hpp
- libs/config/tests/snapshots/lints__config_error_c13_config_this_call.snap
requires the `hints_and_notes` change from #909
```
help[L-C13]: Unnecessary `_this` in `call`
┌─ addons/main/config.cpp:10:14
│
10 │ statement = "_this call f;";
│              ^^^^^^^^^^^^^
│
= note: `call` inherits `_this` from the calling scope
= help: Remove `_this` from the call
```
> config: Add lint C13 for `_this call` in config text

- libs/preprocessor/src/codes/pe29_circular_include.rs
- libs/preprocessor/src/processor/directives.rs
- libs/preprocessor/src/processor/mod.rs
- libs/preprocessor/tests/errors.rs
- libs/preprocessor/tests/errors/pe29_circular_include/a.hpp
- libs/preprocessor/tests/errors/pe29_circular_include/b.hpp
- libs/preprocessor/tests/errors/pe29_circular_include/source.hpp
- libs/preprocessor/tests/errors/pe29_circular_include/stderr.ansi
Fixes #914 
I can see some rare cases where this is allowed with `#if` and other checks, but I think that's rare enough that this PR is fine instead of crashing
> preprocessor: detect circular includes

- libs/config/src/analyze/lints/c12_math_could_be_unquoted.rs
Is there a reason not to check all numbers by default?
if getText is used, it should work fine, and I'd imagine number -> string is a faster conversion than string -> number if the mismatched functions are being used
> config: c12 options

- bin/src/lib.rs
- bin/src/main.rs
Had HEMTT hang for a brief bit at the start, was DNS being slow
This will also print the update message below everything else, making it more visible if the user has warnings
> common: run update check on a different thread

- bin/src/modules/file_patching.rs
at least on windows this has been giving me problems
```
TRACE ThreadId(01) removing existing symlink at F:\SteamLibrary\steamapps\common\Arma 3\z\test
ERROR ThreadId(01) Failed to execute command:
IO Error: Access is denied. (os error 5)
```
> dev: remove linked dir

- libs/config/src/analyze/lints/c12_math_could_be_unquoted.rs
- libs/config/tests/lints/c12_math_could_be_unquoted.hpp
- libs/config/tests/snapshots/lints__config_error_c12_math_could_be_unquoted.snap
- `text = "0-9"; // ignored because name`
blocklist "text", "name", "displayname" should reduce any possible false positives
- ` initSpeed = "300"; // forced because name`
not sure about this part or what entries should be, just an option
> config: Have c12 ignore configs that are usually strings

- bin/dist/profile/autotest/ps_previews.VR/fnc_export.sqf
Filter out `scope = 0` classes, since these can't be used in-game and would cause HEMTT to crash since the preview images are never made.
> photoshoot: only create previews for scope >0 classes

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/utils/bom.rs
- hls/languages/config.json
- hls/package.json
There is some documentation where rapifiable config formats are listed, but were not updated in #979. There is also some other code where only some Arma config formats are listed but not all.
- `--help` documentation for `--no-rap`
- Language server "Arma config" file extensions
- Allowed extensions for BOM stripping
This PR updates them all with the complete list of config formats.
> Update rapifiable formats to all places where they are mentioned

- libs/config/src/analyze/lints/collect_cfgfunctions.rs
- libs/config/tests/lints/collect_cfgfunctions.hpp
- libs/config/tests/snapshots/lints__collect_cfgfunctions.snap
```
class Interface {
file = "\x\enh\addons\main\functions\interface";
class 3DENMinimap;
class assetBrowser_collapse;
```
it assumed people would do `class 3DENMinimap {};` 
defining them as externals was unexpected (but is valid I guess)
> config: Fix not collecting CfgFunctions defined as extern

- libs/sqf/src/analyze/lints/s29_function_undefined.rs
> sqf: S29 - Skip checking undefined functions for `--just` builds
