- src/project.rs
It's nicely aligned with the rest of the keywords.
Can probably make it configurable via JSON in addition if wanted, but those are the most common ones.
> Match 'PATCH' for version reading

- README.md
- docs/README.md
- docs/getting_started.md
- docs/json.md
- docs/usage.md
- Expand root `README.md`
- Add badges
- Nicer descriptions
- Contributing section
- Expand `docs/README.md`
- Fix "Profile" to "Project" for `hemtt.json` documentation
> Expand base documentation

- .travis.yml
- Cargo.lock
- appveyor.yml
- ci/version.ps1
- ci/version.sh
> semver build on ci

- Cargo.lock
- docs/json.md
- docs/usage.md
- src/build.rs
- src/main.rs
- src/project.rs
- Add `--opts` to `build`
- Add `optionals` to `hemtt.json`
- Close #18
> Optional Addons

- docs/json.md
- docs/usage.md
- src/build.rs
- src/main.rs
- src/project.rs
- Close #22
- Change the usage of --opts
> Build Feature - change --opts, add --skip

- docs/usage.md
- src/build.rs
- src/files.rs
- src/main.rs
> Build Feature - Build specific addons

- Cargo.lock
- Cargo.toml
- src/build/sign.rs
- src/error.rs
- src/files.rs
- src/helpers/mod.rs
- src/main.rs
- src/project.rs
- src/template.rs
- src/utilities/translation.rs
- Add basic templating for `hemtt.json` using [handlebars](https://github.com/sunng87/handlebars-rust)
- Replace `print_error(true)` with `unwrap_or_print()`
- Replace `print_error(false)` with `print()`
> Templating

- src/main.rs
- src/project.rs
- src/utilities/convert.rs
- src/utilities/translation.rs
> Look upwards for HEMTT project file

- Cargo.lock
- docs/templating.md
- docs/utilities.md
- src/build/script.rs
- src/main.rs
- src/project.rs
- src/template.rs
- src/utilities/mod.rs
- src/utilities/zip.rs
> SemVer templating

- appveyor.yml
- Add setup.exe to non tagged builds
> dev builds windows installer

- Cargo.lock
- Cargo.toml
- src/utilities/zip.rs
- Fix #91 
- Use new functions from `zip-rs 0.5.2`
> Fix zip using backslash on Windows

- Dockerfile
> Add missing libcurl3 to Dockerfile

- src/main.rs
> Fix usage typo (compontents)

- src/build/sign.rs
- src/project.rs
- Title - Signatures fixed in https://github.com/KoffeinFlummi/armake2/commit/933735ee0dd9212080682f35706ebe5c79ae1dfe
> Default to v3 signatures

- docs/project.md
> Document `PATCHLVL` in `version`

- .travis.yml
- appveyor.yml
> CI - Build x64 first

- .travis.yml
- ci/version.sh
- Enable macOS builds on Travis
> Enable macOS builds on Travis

- .github/workflows/rust.yml
> GitHub Workflows

- docs/project.md
- src/commands/build/mod.rs
- src/commands/build/postbuild/release.rs
- src/commands/clean.rs
- src/commands/init.rs
- src/commands/pack.rs
- src/commands/status.rs
- src/commands/template/mod.rs
- src/commands/update.rs
- src/flow/script/mod.rs
- src/lib.rs
- src/macros/mod.rs
- src/utilities/mission_generate.rs
- src/utilities/zip.rs
> General Tweaks

- src/commands/build/checks/clear.rs
- src/files.rs
- src/lib.rs
- src/macros/fs.rs
- src/utilities/convert.rs
- src/utilities/filepatching.rs
- src/utilities/mod.rs
> Utility - File Patching

- Cargo.lock
- src/commands/template/mod.rs
- src/commands/template/version.rs
- src/project/mod.rs
- Fix `template init`
- Add version to variables
> Fix Template

- docs/project.md
- src/commands/build/addon.rs
- src/commands/build/postbuild/sign.rs
- src/project/mod.rs
- Re-implement #132 in restructure
- Close #224
> Re-implement folder optionals in restructure

- src/project/signing.rs
> Fix signing with no prefix defined

- src/project/mod.rs
- Fix #267 
Not pretty, it works. Could setup a nicer data store to check both, but there is no plan to support anything else.
> Fix too broad configuration file search

- src/flow/script/task.rs
- Fix `steps_linux` to run at all in restructure.
Explanation: https://github.com/rust-lang/rust/issues/26726
> Fix `steps_linux` Linux check

- .github/workflows/rust.yml
- Ensure that HEMTT builds on macOS
> Add macOS to GitHub Actions CI

- .github/workflows/rust.yml
> OpenSSL 1.1.1g for Windows CI build

- .github/workflows/rust.yml
- Make Upload step look nicer in CI steps list
> Add name for upload artifact CI step

- .github/workflows/clippy.yml
- .github/workflows/rust.yml
- Trigger GitHub actions for pull requests from forked repositories
> Trigger GitHub Actions for pull requests

- src/lib.rs
- src/render/helpers/mod.rs
- src/utilities/render_var.rs
> Git Helper: commitCount

- .github/workflows/rust.yml
- Upload unique artifacts to draft release
> Upload release artifacts with proper names

- README.md
> Update GitHub links in README

- src/commands/build/build.rs
- Behave like Mikero Tools
- Save me from wasting time on troubleshooting why CfgFunctions won't load properly
> Trim leading and trailing slashes from pbo prefix header

- .github/workflows/rust.yml
- src/commands/build/build.rs
- src/commands/template/mod.rs
- src/lib.rs
- src/utilities/mission_generate.rs
- Fix current warnings
- Fail future warnings
> Fix warnings in CI builds

- bin/app/src/commands/new.rs
> create `.hemtt` before creating `.hemtt/project.toml`

- Cargo.lock
- Cargo.toml
- bin/Cargo.toml
- bin/src/commands/launch.rs
- bin/src/config/project/hemtt.rs
> Launch - Support for DLC

- Cargo.lock
- bin/Cargo.toml
- bin/src/commands/launch.rs
- bin/src/config/project/hemtt.rs
- bin/src/config/project/mod.rs
- bin/src/error.rs
- bin/tests/alpha/.hemtt/project.toml
- book/commands/launch.md
- libs/arma/src/dlc.rs
> Launch - Profiles

- bin/src/config/addon/mod.rs
- bin/src/modules/binarize.rs
- bin/src/modules/pbo.rs
- bin/src/modules/rapifier.rs
- book/configuration/addon.md
Change all the fields to be objects to match the style of project.toml and allow further options in the future
> refactor addon config

- book/commands/launch.md
- libs/arma/src/dlc.rs
> Launch - Add Spearhead 1944 Creator DLC support

- libs/config/src/parse/str.rs
> config: handle multiline strings

- book/commands/launch.md
> [Hemtt Book] added Example for "Launch Editor Mission" Parameter

- libs/preprocessor/src/defines.rs
- libs/preprocessor/tests/bootstrap/define_builtin/expected.hpp
Should fix #567, or atleast many of them
> Preprocessor: quote __file__

- Cargo.lock
- bin/Cargo.toml
- bin/src/commands/launch.rs
- bin/src/error.rs
- book/commands/launch.md
- libs/common/src/project/hemtt.rs
> Launch: support for presets

- bin/src/modules/file_patching.rs
Fix https://github.com/BrettMayson/HEMTT/issues/494#issuecomment-1790861788
> Fix dev symlinks on Linux

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/commands/release.rs
- bin/src/commands/script.rs
- bin/src/context.rs
- bin/src/lib.rs
- bin/src/link.rs
- bin/src/modules/pbo.rs
- book/commands/build.md
- book/commands/dev.md
- book/commands/index.md
Warnings every time it is used, because I really don't want people using this
Close #595
> support for --just in dev and build

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/commands/mod.rs
- bin/src/commands/release.rs
- bin/src/commands/script.rs
- bin/src/commands/value.rs
- bin/src/context.rs
- bin/src/lib.rs
- bin/src/modules/mod.rs
- bin/src/modules/sign.rs
- bin/src/report/mod.rs
- bin/src/utils/pbo/unpack.rs
- libs/common/src/project/version.rs
Implements a basic version of #625
> Value: basic value command

- bin/src/context.rs
- bin/src/modules/binarize/mod.rs
> Binarize: link all addons when using --just

- bin/src/commands/new/mod.rs
- bin/src/lib.rs
- bin/tests/build.rs
- bin/tests/new.rs
> new: don't write ci annotations

- libs/preprocessor/src/processor/directives.rs
- libs/preprocessor/tests/bootstrap.rs
- libs/preprocessor/tests/bootstrap/if_digits/expected.hpp
- libs/preprocessor/tests/bootstrap/if_digits/source.hpp
- libs/preprocessor/tests/errors/pe2_unexpected_eof/stderr.ansi
> Preprocessor: fix #if parsing of tokens

- Cargo.lock
- Cargo.toml
- bin/src/commands/new/mod.rs
- bin/src/modules/sqf.rs
- book/SUMMARY.md
- book/configuration/custom-commands.md
- hls/package-lock.json
- hls/src/sqf/hover.rs
- hls/src/sqf/locate.rs
- hls/src/sqf/mod.rs
- hls/src/workspace.rs
- libs/sqf/src/error.rs
- libs/sqf/src/parser/database/mod.rs
- libs/sqf/tests/analyze.rs
- libs/sqf/tests/errors.rs
- libs/sqf/tests/preprocessor.rs
- libs/sqf/tests/simple.rs
> SQF: custom command support

- Cargo.lock
- Cargo.toml
- bin/Cargo.toml
- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/commands/launch/error/bcle6_launch_config_not_found.rs
- bin/src/commands/mod.rs
- bin/src/commands/wiki.rs
- bin/src/lib.rs
- bin/src/modules/sqf.rs
- hls/build.rs
- hls/src/sqf/mod.rs
- libs/common/src/lib.rs
- libs/preprocessor/src/codes/pe9_function_call_argument_count.rs
- libs/sqf/src/analyze/codes/mod.rs
- libs/sqf/src/analyze/codes/sae1_require_version_command.rs
- libs/sqf/src/analyze/codes/sae2_require_version_event.rs
- libs/sqf/src/analyze/codes/saw1_unknown_event.rs
- libs/sqf/src/analyze/codes/saw2_wrong_event_command.rs
- libs/sqf/src/analyze/event_handlers.rs
- libs/sqf/src/analyze/if_assign.rs
- libs/sqf/src/analyze/mod.rs
- libs/sqf/src/analyze/required_version.rs
- libs/sqf/src/parser/database/mod.rs
- libs/sqf/tests/analyze.rs
- libs/sqf/tests/errors.rs
- libs/sqf/tests/preprocessor.rs
- libs/sqf/tests/simple.rs
- Check if events exist, provide did you mean
- Check if the correct command is used for the event
- Check if the required version meets event usage requirements
- UserAction is not included, pending more wiki parsing
- Displays a warning when building a mod that requires a version later than current stable (the misc)
> sqf: event handlers

- book/installation.md
Better highlighted recommended installation method. Added warning and note boxes.
> Book: Update Installation

- bin/src/commands/dev.rs
- book/commands/dev.md
- book/commands/launch.md
Allows dev-builds / launching the game with unrapified configs
> Add `--no-rap` param to dev/launch

- bin/src/modules/hook/error/bhe4_runtime_error.rs
- bin/src/modules/hook/libraries/rfs/path.rs
- bin/src/modules/hook/libraries/vfs/path.rs
- bin/src/modules/hook/mod.rs
> hooks: fix runtime error, fs on const

- bin/src/lib.rs
> fix crash with no argument, use single -v as version

- libs/preprocessor/src/codes/pe7_if_unit_or_function.rs
- libs/preprocessor/src/codes/pe9_function_call_argument_count.rs
- libs/preprocessor/src/defines.rs
- libs/preprocessor/src/processor/defines.rs
- libs/preprocessor/src/processor/directives.rs
- libs/preprocessor/tests/bootstrap.rs
- libs/preprocessor/tests/bootstrap/define_variable_recursion/expected.hpp
- libs/preprocessor/tests/bootstrap/define_variable_recursion/source.hpp
> preprocessor: fix recursion on argument variables

- Cargo.lock
- Cargo.toml
- bin/src/commands/utils.rs
- bin/src/utils/mod.rs
- bin/src/utils/sqf/case.rs
- bin/src/utils/sqf/mod.rs
- hls/build.rs
- libs/sqf/src/analyze/codes/mod.rs
- libs/sqf/src/analyze/codes/saa6_command_case.rs
- libs/sqf/src/analyze/codes/saw2_wrong_event_command.rs
- libs/sqf/src/analyze/command_case.rs
- libs/sqf/src/analyze/mod.rs
- libs/sqf/src/lib.rs
- libs/sqf/src/parser/database/mod.rs
- libs/sqf/tests/analyze.rs
- libs/sqf/tests/analyze/saa6_command_case/source.sqf
- libs/sqf/tests/analyze/saa6_command_case/stdout.ansi
> sqf: check command casing

- .github/workflows/build.yaml
- libs/config/src/analyze/lints/c03_duplicate_classes.rs
- libs/config/src/analyze/lints/c04_external_missing.rs
- libs/config/src/analyze/lints/c05_external_parent_case.rs
- libs/config/src/analyze/lints/c10_class_missing_braces.rs
- libs/config/src/model/class.rs
- libs/config/src/parse/mod.rs
- libs/config/src/parse/property.rs
- libs/config/tests/lints.rs
- libs/config/tests/lints/c10_class_missing_braces/source.hpp
- libs/config/tests/lints/c10_class_missing_braces/stdout.ansi
> config: class with inheritance need braces

- libs/sqf/src/analyze/lints/s18_in_vehicle_check.rs
- libs/sqf/tests/lints.rs
- libs/sqf/tests/lints/s18_in_vehicle_check/source.sqf
- libs/sqf/tests/lints/s18_in_vehicle_check/stdout.ansi
> sqf: in vehicle check should use objectParent

- Cargo.lock
- bin/Cargo.toml
- bin/src/lib.rs
- bin/src/modules/archive.rs
- bin/src/modules/files.rs
- bin/src/modules/pbo.rs
- bin/src/modules/rapifier.rs
- bin/src/modules/sqf.rs
- bin/src/progress.rs
Doesn't show up in CI
[Screencast From 2024-10-21 18-23-46.webm](https://github.com/user-attachments/assets/f7bbb1b6-6ef1-4567-9eb9-ce8b73faf883)
> progress bar

- bin/src/commands/launch/launcher.rs
> launch: fix launch on linux

- bin/src/commands/photoshoot/mod.rs
- libs/common/src/config/project/hemtt/launch.rs
> photoshoot: clear configured mission

- bin/src/commands/dev.rs
- bin/src/commands/launch/mod.rs
- bin/src/commands/photoshoot/mod.rs
> photoshoot: binarize

- libs/sqf/src/analyze/lints/s24_marker_spam.rs
> SQF - Handle setMarkerDrawPriority

- book/install.sh
> install: use sh only

- libs/common/src/config/project/lint.rs
- libs/common/src/error.rs
> lints - fix `LintsConfigConflict` error for stringtables

- libs/config/build.rs
- libs/preprocessor/build.rs
- libs/preprocessor/src/codes/pe27_unexpected_endif.rs
- libs/preprocessor/src/codes/pe28_unexpected_else.rs
- libs/preprocessor/src/ifstate.rs
- libs/preprocessor/src/processor/directives.rs
- libs/preprocessor/tests/errors.rs
- libs/preprocessor/tests/errors/pe27_unexpected_endif/source.hpp
- libs/preprocessor/tests/errors/pe27_unexpected_endif/stderr.ansi
- libs/preprocessor/tests/errors/pe28_unexpected_else/source.hpp
- libs/preprocessor/tests/errors/pe28_unexpected_else/stderr.ansi
- libs/sqf/build.rs
- libs/stringtable/build.rs
Fix https://github.com/BrettMayson/HEMTT/issues/896
`println!("cargo:rerun-if-changed=src/analyze/lints");` 
fixes problem with automod not seeing new files
ref https://github.com/dtolnay/automod/issues/22
> preprocessor: Error for unexpcted `#else` or `#endif`

- Cargo.lock
- Cargo.toml
- hls/Cargo.toml
- libs/config/Cargo.toml
- libs/preprocessor/Cargo.toml
- libs/preprocessor/src/parse/mod.rs
[ACE current master](https://github.com/acemod/ACE3/commit/35a798aefc0aeb5b7b85fde73b8fdff7fbd45954) goes 30s to 18s user on my machine
> preprocessor - cache file tokenization for common includes

- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- libs/common/src/config/project/hemtt/mod.rs
- libs/stringtable/src/analyze/lints/l02_usage/mod.rs
ref: https://discord.com/channels/976165959041679380/1039189045655392389/1345096320268107978
> stringtable: Skip usage lints when using `--just`

- bin/src/commands/utils.rs
- bin/src/modules/bom.rs
- bin/src/utils/bom.rs
- bin/src/utils/mod.rs
> utils: remove bom

- libs/config/src/analyze/lints/c11_file_type.rs
- libs/config/src/analyze/lints/c12_math_could_be_unquoted.rs
- libs/config/tests/lints/c12_math_could_be_unquoted.hpp
- libs/config/tests/snapshots/lints__config_error_c12_math_could_be_unquoted.snap
ref https://github.com/acemod/ACE3/pull/10795#discussion_r1988264246
> config: Deep search arrays for lints c11/c12

- bin/src/commands/launch/mod.rs
- bin/src/modules/file_patching.rs
> dev: filepatching, better warnings if unable to

- book/time.js
> book: fix search and themes

- bin/src/utils/bom.rs
- hls/package.json
> utils(bom): fix file length after removing BOM characters

- hls/src/config/lints.rs
- hls/src/sqf/lints.rs
> hls: supress includes

- hls/package-lock.json
- hls/package.json
- hls/webview-src/p3d/viewer.js
- Add Navigation Gizmo
- Add Focus Camera Key(currently F)
- Improve Lighting setup by adding Fog and change grid rendering
> Improve P3D viewer

- libs/config/src/analyze/lints/c12_math_could_be_unquoted.rs
- libs/config/tests/lints/c12_math_could_be_unquoted.hpp
- libs/config/tests/lints/project_tests.toml
- libs/config/tests/snapshots/lints__config_error_c12_math_could_be_unquoted.snap
ref https://discord.com/channels/976165959041679380/1039189045655392389/1351199509094600846
> config: Fix C12 case sensitivity on ignore option

- hls/package-lock.json
- hls/package.json
- hls/vscode-src/paa/viewer.ts
- hls/webview-src/paa/viewer.js
Preview: 
https://github.com/user-attachments/assets/52b125f8-5eaa-4508-84f4-b3842effbeae
> Add Color Channel View in PAA Viewer

- bin/src/utils/config/derapify.rs
- bin/src/utils/config/mod.rs
> utils: derapify

- bin/src/modules/hook/libraries/version.rs
- libs/common/src/version.rs
As requested on Discord. Tested locally.
> rhai: Add git hash function

- bin/src/commands/value.rs
- bin/src/modules/hook/libraries/project.rs
- libs/common/src/config/project/mod.rs
> project: author support

- bin/src/commands/dev.rs
- bin/src/commands/photoshoot/mod.rs
- bin/src/lib.rs
> photoshoot: use binarize launch profile setting

- arma/src/photoshoot.rs
- bin/dist/profile/autotest/ps_items.VR/functions/fnc_firearm.sqf
- bin/dist/profile/autotest/ps_items.VR/functions/fnc_headgear.sqf
- bin/dist/profile/autotest/ps_items.VR/functions/fnc_uniform.sqf
- bin/dist/profile/autotest/ps_items.VR/functions/fnc_vest.sqf
> photoshoot: fix items

- libs/config/src/parse/property.rs
- libs/config/tests/lints/c01_invalid_value.hpp
- libs/config/tests/snapshots/lints__config_error_c01_invalid_value.snap
> config: improve unquoted parsing after valid values

- libs/config/src/parse/property.rs
- libs/config/tests/lints.rs
- libs/config/tests/lints/c08_class_missing_final_brace.hpp
- libs/config/tests/snapshots/lints__config_error_c08_class_missing_final_brace.snap
> config: handle unclosed classes

- bin/src/modules/rapifier.rs
- libs/sqf/src/analyze/lints/s02_event_handlers.rs
- libs/sqf/src/analyze/lints/s29_function_undefined.rs
- libs/sqf/tests/lints.rs
- libs/workspace/src/addons.rs
- libs/workspace/src/reporting/processed.rs
- Changed the message to show the first location explicitly
- Added "Did you mean"
> sqf: improve undefined function diag

- bin/src/report.rs
- libs/preprocessor/src/codes/pe13_include_not_encased.rs
- libs/preprocessor/src/processor/directives.rs
- libs/preprocessor/tests/errors.rs
- libs/preprocessor/tests/errors/pe13_include_not_encased/source.hpp
- libs/preprocessor/tests/errors/pe13_include_not_encased/stderr.ansi
- libs/preprocessor/tests/errors/pe13_include_not_encased_end_only/source.hpp
- libs/preprocessor/tests/errors/pe13_include_not_encased_end_only/stderr.ansi
- libs/preprocessor/tests/errors/pe13_include_not_encased_start_only/source.hpp
- libs/preprocessor/tests/errors/pe13_include_not_encased_start_only/stderr.ansi
> preprocessor: fix not enclosed includes

- bin/src/modules/hook/libraries/rfs/path.rs
> hooks: fix directory copy on real file system

- Cargo.lock
- bin/Cargo.toml
- bin/src/commands/build.rs
- bin/src/commands/dev.rs
- bin/src/modules/mod.rs
- bin/src/modules/summary.rs
```
Build Summary:
PBOs  : 258.07 MB
Files : 1.11 MB
Total : 259.18 MB
````
Just thought it would be something neat, not sure if we need it, open to opinions or other things to add than just size
> bin: build summary

- libs/workspace/src/reporting/files.rs
> diags: fix reporting lines on crlf files

- libs/config/src/analyze/lints/c14_unused_external.rs
> config: fix c14 creating .hemttout

- libs/sqf/src/analyze/lints/s30_configof.rs
- libs/sqf/src/lib.rs
- libs/sqf/tests/lints.rs
- libs/sqf/tests/lints/s30_configof.sqf
- libs/sqf/tests/snapshots/lints__simple_s30_configof.snap
> sqf: S30 configOf

- bin/src/commands/launch/error/bcle11_pointer_not_found.rs
- bin/src/commands/launch/launcher.rs
- bin/src/commands/launch/mod.rs
- libs/sqf/src/analyze/lints/s17_var_all_caps.rs
> bin - fix `launch` on windows

- bin/src/utils/audio/convert.rs
- bin/src/utils/config/derapify.rs
- bin/src/utils/p3d/json.rs
- bin/src/utils/pbo/extract.rs
> utils: create directories

- libs/sqf/src/analyze/inspector/mod.rs
- libs/sqf/src/analyze/lints/s14_unused.rs
- libs/sqf/tests/inspector/test_1.sqf
> Inspector - Support ignoring unused vars
